# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

variables:
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build and push stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
      - task: AzureContainerApps@1
        inputs:
          appSourcePath: '$(System.DefaultWorkingDirectory)'
          azureSubscription: 'Ansalemo(4388fa06-bf66-4497-82c2-991ba75ecb97)'
          acrName: 'ansalemoacr'
          acrUsername: 'ansalemoacr'
          acrPassword: 'MhhPJHD6nvai0INncrFtSbzg35eEtodKLyTyvloR0x+ACRCfyHm6'
          imageToBuild: 'ansalemoacr.azurecr.io/ansalemo-aca-ado:latest'
          containerAppName: 'ansalemo-azure-devops'
          resourceGroup: 'ansalemo-rg'
          containerAppEnvironment: 'ansalemo-caenv'
          runtimeStack: 'go:1.19'
          targetPort: '3000'
          location: 'eastus'